name: Next.js CI/CD

on:
  push:
    branches:
      - main  # Ejecuta la pipeline en cada push a la rama main
  pull_request:
    branches:
      - main  # También ejecuta la pipeline en los pull requests a main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Clona el repositorio

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Define la versión de Node.js (ajústalo según tu proyecto)

      - name: Install dependencies
        run: npm install

      #- name: Run tests
      #  run: npm test  # Asegúrate de tener pruebas configuradas en tu proyecto

      - name: Lint code
        run: npm run lint  # Opcional: Ejecuta un linter si está configurado

      - name: Build Next.js application
        run: npm run build  # Compila la aplicación Next.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Solo ejecuta el despliegue en la rama main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js application
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20  # Usa una acción de GitHub para desplegar en Vercel
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Configura el token secreto de Vercel
          vercel-args: '--prod'  # Despliegue en producción
          working-directory: ./  # Directorio raíz del proyecto
