name: Node.js CI with trpc and Express

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Define la versión de Node.js

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript compiler
        run: npm run build  # Si usas TypeScript, esto compilará el proyecto

      #- name: Run tests
      #  run: npm test  # Asegúrate de tener tests en tu proyecto

      #- name: Lint code
      #  run: npm run lint  # Si tienes configurado un linter (opcional)

      - name: Start the server (for integration tests)
        run: npm start &  # Inicia el servidor en segundo plano

      - name: Wait for the server to start
        run: sleep 10  # Espera 10 segundos para que el servidor se inicie

      #- name: Run Integration tests (if applicable)
      #  run: npm run integration-test  # Si tienes pruebas de integración

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Deploy to server
        run: |
          # Aquí puedes agregar tu script de despliegue, por ejemplo,
          # usando FTP, AWS, Heroku, etc.
          echo "Deploying to the server..."  # Script de despliegue
